FROM python:3.12

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

ARG SECRET_KEY
ARG ALLOWED_HOSTS
ARG GRAFANAURL
ARG GRAFANAUSERID
ARG GRAFANATOKEN
ARG DISCORDURL

ENV SECRET_KEY=$SECRET_KEY
ENV ALLOWED_HOSTS=$ALLOWED_HOSTS
ENV GRAFANAURL=$GRAFANAURL
ENV GRAFANAUSERID=$GRAFANAUSERID
ENV GRAFANATOKEN=$GRAFANATOKEN
ENV DISCORDURL=$DISCORDURL

WORKDIR /app

COPY . .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

RUN python manage.py collectstatic --noinput
RUN python manage.py makemigrations && python manage.py migrate

EXPOSE 8000