services:
  extractor:
    image: sopio/acha-extractor:latest
    restart: unless-stopped
    container_name: extractor
    working_dir: /app
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - INFO_DISCORDURL=${INFO_DISCORDURL}
      - WARNING_DISCORDURL=${WARNING_DISCORDURL}
    volumes:
      - /home/ubuntu/app/static:/static
      - ${LOG_PATH}:/app/logs
    command: >
      sh -c "gunicorn Extractor.wsgi:application --workers 3 --threads 4 --preload --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    networks:
      - extractor-network

networks:
  extractor-network:
    driver: bridge
    external: true
