services:
  extractor:
    build:
      context: ../
      dockerfile: ./Dockerfile
    container_name: extractor
    working_dir: /app
    env_file:
      - ../.env
    volumes:
      - ../:/app
    entrypoint:
      [
        "/bin/sh",
        "-c",
        "python manage.py makemigrations && python manage.py migrate && gunicorn Extractor.wsgi:application --workers 3 --threads 4 --reload --bind 0.0.0.0:8000",
      ]
    ports:
      - "8000:8000"
