services:
  extractor:
    image: sopio/acha-extractor:latest
    container_name: extractor
    working_dir: /app
    volumes:
      - /home/ubuntu/app/static:/static
    command: >
      sh -c "gunicorn Extractor.wsgi:application --workers 3 --threads 4 --preload --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    networks:
      - extractor-network

networks:
  extractor-network:
    driver: bridge
    external: true
