services:
  extractor:
    build:
      context: ../
      dockerfile: ./Dockerfile
    container_name: extractor
    working_dir: /app
    environment:
      - SECRET_KEY=""
      - ALLOWED_HOSTS="*"
      - DISCORDURL=""
    command: >
      sh -c "python manage.py makemigrations &&
        python manage.py migrate &&
        gunicorn Extractor.wsgi:application --bind 0.0.0.0:80"
    ports:
      - "80:80"